#Tomcat server port number 8080
server.port=8080
server.servlet.session.persistent=false
#DB properties
spring.datasource.url=jdbc:mysql://localhost:3306/collegeduniyadb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=UeBa_2020
# JPA properties
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect


#Disable open session in view
spring.jpa.open-in-view=false

#Dmart Config
#server.port=8081
#spring.datasource.url=jdbc:mysql://localhost:3306/dmartdb
##spring.datasource.url=jdbc:mysql://localhost:3306/db_example
#spring.datasource.username=root
#spring.datasource.password=UeBa_2020
#
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLInnoDBDialect
#
#spring.jpa.hibernate.ddl_auto=update
#
##for ssl only
#server.ssl.key-alias=shri-https-key
#server.ssl.key-store=classpath:dmartkeystore.jks
#server.ssl.key-store-type=JKS
#server.ssl.key-store-password=password
##server.ssl.enabled=true